name: Triage
on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - master
    paths:
      - 'xep-*.xml'
jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml2-utils
          version: cachetag1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup master branch locally without switching current branch
        run: git fetch origin master:master
      - run: bash tools/github_auto_triage_pr.sh ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
